// This is a manual mapping mastered here
const DisplayMap = require("./DisplayMap.json");

// This is generated by <proj root>./scripts/deploy/deploy.js and exported here by
// <proj root>/.scripts/updateFrontEnd.js
const addressConfig = require("./contractAddressesConfig.json");

// These are exported here by <proj root>./scripts/updateFrontEnd.js
const equityPriceABI = require("./EquityPrice.json");
const FXPriceABI = require("./FXPrice.json");
const ERC20AppleStableShare = require("./ERC20AppleStableShare.json");
const ERC20CNYStableCoin = require("./ERC20CNYStableCoin");
const ERC20EURStableCoin = require("./ERC20EURStableCoin");
const ERC20USDStableCoin = require("./ERC20USDStableCoin");
const EscrowStableCoinABI = require("./EscrowCurrenyAccount.json");
const FXDeal = require("./FXDeal.json");
const SimpleOption = require("./SimpleOption.json");
const SimplePutOption = require("./SimplePutOption.json");
const HelloWorldABI = require("./HelloWorld.json");
const HelloWorldByteCode = require("./HelloWorld-bytecode.json");

module.exports = {
  addressConfig,
  DisplayMap,
  equityPriceABI,
  FXPriceABI,
  ERC20AppleStableShare,
  ERC20CNYStableCoin,
  ERC20EURStableCoin,
  ERC20USDStableCoin,
  EscrowStableCoinABI,
  FXDeal,
  SimpleOption,
  SimplePutOption,
  HelloWorldABI,
  HelloWorldByteCode
};
