
function randomWords() {
    nameIdx = Math.floor(Math.random() * randomNames.length);
    adjectiveIdx = Math.floor(Math.random() * randomAdjectives.length);
    return `${randomAdjectives[adjectiveIdx]}-${randomNames[nameIdx]}`;
}

function randomSentence() {
    sentenceIdx = Math.floor(Math.random() * randomSentences.length);
    return `${randomSentences[sentenceIdx]}`;
}

module.exports = {
    randomWords,
    randomSentence
}

randomNames = ["Ronald",
    "Dorothy",
    "Jason",
    "Rebecca",
    "Edward",
    "Sharon",
    "Jeffrey",
    "Laura",
    "Ryan",
    "Cynthia",
    "Jacob",
    "Amy",
    "Gary",
    "Kathleen",
    "Nicholas",
    "Angela",
    "Eric",
    "Shirley",
    "Jonathan",
    "Brenda",
    "Stephen",
    "Emma",
    "Larry",
    "Anna",
    "Justin",
    "Pamela",
    "Scott",
    "Nicole",
    "Brandon",
    "Samantha",
    "Benjamin",
    "Katherine",
    "Samuel",
    "Christine",
    "Gregory",
    "Helen",
    "Alexander",
    "Debra",
    "Patrick",
    "Rachel",
    "Frank",
    "Carolyn",
    "Raymond",
    "Janet",
    "Jack",
    "Maria",
    "Dennis",
    "Catherine",
    "Jerry",
    "Heather",
    "Tyler",
    "Diane",
    "Aaron",
    "Olivia",
    "Jose",
    "Julie",
    "Adam",
    "Joyce",
    "Nathan",
    "Victoria",
    "Henry",
    "Ruth",
    "Zachary",
    "Virginia",
    "Douglas",
    "Lauren",
    "Peter",
    "Kelly",
    "Kyle",
    "Christina",
    "Noah",
    "Joan",
    "Ethan",
    "Evelyn",
    "Jeremy",
    "Judith",
    "Walter",
    "Andrea",
    "Christian",
    "Hannah",
    "Keith",
    "Megan",
    "Roger",
    "Cheryl",
    "Terry",
    "Jacqueline",
    "Austin",
    "Martha",
    "Sean",
    "Madison",
    "Gerald",
    "Teresa",
    "Carl",
    "Gloria",
    "Harold",
    "Sara",
    "Dylan",
    "Janice",
    "Arthur",
    "Ann",
    "Lawrence",
    "Kathryn",
    "Jordan",
    "Abigail",
    "Jesse",
    "Sophia",
    "Bryan",
    "Frances",
    "Billy",
    "Jean",
    "Bruce",
    "Alice",
    "Gabriel",
    "Judy",
    "Joe",
    "Isabella",
    "Logan",
    "Julia",
    "Alan",
    "Grace",
    "Juan",
    "Amber",
    "Albert",
    "Denise",
    "Willie",
    "Danielle",
    "Elijah",
    "Marilyn",
    "Wayne",
    "Beverly",
    "Randy",
    "Charlotte",
    "Vincent",
    "Natalie",
    "Mason",
    "Theresa",
    "Roy",
    "Diana",
    "Ralph",
    "Brittany",
    "Bobby",
    "Doris",
    "Russell",
    "Kayla",
    "Bradley",
    "Alexis",
    "Philip",
    "Lori",
    "Eugene",
    "Marie"]



randomAdjectives = ["adorable",
    "adventurous",
    "aggressive",
    "agreeable",
    "alert",
    "alive",
    "amused",
    "angry",
    "annoyed",
    "annoying",
    "anxious",
    "arrogant",
    "ashamed",
    "attractive",
    "average",
    "awful",
    "bad",
    "beautiful",
    "better",
    "bewildered",
    "black",
    "bloody",
    "blue",
    "blue-eyed",
    "blushing",
    "bored",
    "brainy",
    "brave",
    "breakable",
    "bright",
    "busy",
    "calm",
    "careful",
    "cautious",
    "charming",
    "cheerful",
    "clean",
    "clear",
    "clever",
    "cloudy",
    "clumsy",
    "colorful",
    "combative",
    "comfortable",
    "concerned",
    "condemned",
    "confused",
    "cooperative",
    "courageous",
    "crazy",
    "creepy",
    "crowded",
    "cruel",
    "curious",
    "cute",
    "dangerous",
    "dark",
    "dead",
    "defeated",
    "defiant",
    "delightful",
    "depressed",
    "determined",
    "different",
    "difficult",
    "disgusted",
    "distinct",
    "disturbed",
    "dizzy",
    "doubtful",
    "drab",
    "dull",
    "eager",
    "easy",
    "elated",
    "elegant",
    "embarrassed",
    "enchanting",
    "encouraging",
    "energetic",
    "enthusiastic",
    "envious",
    "evil",
    "excited",
    "expensive",
    "exuberant",
    "fair",
    "faithful",
    "famous",
    "fancy",
    "fantastic",
    "fierce",
    "filthy",
    "fine",
    "foolish",
    "fragile",
    "frail",
    "frantic",
    "friendly",
    "frightened",
    "funny",
    "gentle",
    "gifted",
    "glamorous",
    "gleaming",
    "glorious",
    "good",
    "gorgeous",
    "graceful",
    "grieving",
    "grotesque",
    "grumpy",
    "handsome",
    "happy",
    "healthy",
    "helpful",
    "helpless",
    "hilarious",
    "homeless",
    "homely",
    "horrible",
    "hungry",
    "hurt",
    "ill",
    "important",
    "impossible",
    "inexpensive",
    "innocent",
    "inquisitive",
    "itchy",
    "jealous",
    "jittery",
    "jolly",
    "joyous",
    "kind",
    "lazy",
    "light",
    "lively",
    "lonely",
    "long",
    "lovely",
    "lucky",
    "magnificent",
    "misty",
    "modern",
    "motionless",
    "muddy",
    "mushy",
    "mysterious",
    "nasty",
    "naughty",
    "nervous",
    "nice",
    "nutty",
    "obedient",
    "obnoxious",
    "odd",
    "old-fashioned",
    "open",
    "outrageous",
    "outstanding",
    "panicky",
    "perfect",
    "plain",
    "pleasant",
    "poised",
    "poor",
    "powerful",
    "precious",
    "prickly",
    "proud",
    "putrid",
    "puzzled",
    "quaint",
    "real",
    "relieved",
    "repulsive",
    "rich",
    "scary",
    "selfish",
    "shiny",
    "shy",
    "silly",
    "sleepy",
    "smiling",
    "smoggy",
    "sore",
    "sparkling",
    "splendid",
    "spotless",
    "stormy",
    "strange",
    "stupid",
    "successful",
    "super",
    "talented",
    "tame",
    "tasty",
    "tender",
    "tense",
    "terrible",
    "thankful",
    "thoughtful",
    "thoughtless",
    "tired",
    "tough",
    "troubled",
    "ugliest",
    "ugly",
    "uninterested",
    "unsightly",
    "unusual",
    "upset",
    "uptight",
    "vast",
    "victorious",
    "vivacious",
    "wandering",
    "weary",
    "wicked",
    "wide-eyed",
    "wild",
    "witty",
    "worried",
    "worrisome",
    "wrong",
    "zany",
    "zealous"];

randomSentences = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    "Facilisis volutpat est velit egestas dui id ornare arcu. ",
    "Cursus in hac habitasse platea dictumst quisque sagittis purus sit. ",
    "obortis mattis aliquam faucibus purus in massa. ",
    "Dui id ornare arcu odio ut. ",
    "Tortor at risus viverra adipiscing at in tellus integer feugiat. ",
    "Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. ",
    "Blandit turpis cursus in hac habitasse platea dictumst.",
    "A quisque. ",
    "Volutpat est velit egestas dui id ornare arcu. ",
    "Ultrices sagittis orci a scelerisque purus semper eget duis at. ",
    "Adipiscing vitae proin sagittis nisl rhoncus mattis. Ornare lectus sit amet est placerat in egestas erat. ",
    "Ac turpis egestas maecenas pharetra convallis posuere morbi. ",
    "Sed nisi lacus sed viverra. ",
    "Tellus elementum sagittis vitae et leo duis ut diam. Metus aliquam eleifend mi in nulla. ",
    "Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. ",
    "Metus dictum at tempor commodo ullamcorper a. ",
    "In iaculis nunc sed augue lacus viverra vitae. ",
    "Elementum nibh tellus molestie nunc non.",
    "Lectus magna fringilla urna porttitor rhoncus. ",
    "Suscipit tellus mauris a diam maecenas sed enim ut. ",
    "Est ante in nibh mauris cursus. ",
    "Purus semper eget duis at tellus at urna condimentum mattis. ",
    "Nibh venenatis cras sed felis. ",
    "Vel pharetra vel turpis nunc eget lorem dolor sed. ",
    "Sed elementum tempus egestas sed sed. ",
    "Lacus vel facilisis volutpat est velit egestas dui id. ",
    "Neque gravida in fermentum et sollicitudin ac orci. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. ",
    "Convallis tellus id interdum velit. ",
    "Ipsum consequat nisl vel pretium lectus quam id. ",
    "Nulla pellentesque dignissim enim sit amet venenatis urna. ",
    "Fames ac turpis egestas integer. ",
    "Enim nulla aliquet porttitor lacus luctus. ",
    "Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. ",
    "Mus mauris vitae ultricies leo. ",
    "Nisi scelerisque eu ultrices vitae auctor eu augue ut. ",
    "Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. ",
    "Cursus turpis massa tincidunt dui ut ornare lectus. ",
    "Morbi tristique senectus et netus et. ",
    "Eget arcu dictum varius duis at consectetur lorem donec massa. ",
    "Sit amet est placerat in egestas erat imperdiet sed euismod. ",
    "Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. ",
    "Nulla aliquet enim tortor at. ",
    "Nunc id cursus metus aliquam eleifend mi. ",
    "A diam maecenas sed enim ut sem viverra aliquet.",
    "Adipiscing commodo elit at imperdiet dui. ",
    "Lectus urna duis convallis convallis. ",
    "In dictum non consectetur a. ",
    "Malesuada fames ac turpis egestas. ",
    "At ultrices mi tempus imperdiet nulla malesuada pellentesque. ",
    "Id aliquet lectus proin nibh nisl condimentum id venenatis a. ",
    "Dolor sit amet consectetur adipiscing. ",
    "Penatibus et magnis dis parturient montes nascetur. ",
    "Mi proin sed libero enim sed. ",
    "At lectus urna duis convallis. ",
    "Habitant morbi tristique senectus et netus et malesuada. ",
    "Ut eu sem integer vitae justo eget magna. ",
    "Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. ",
    "Enim tortor at auctor urna nunc id cursus metus. ",
    "Suspendisse ultrices gravida dictum fusce ut placerat. ",
    "Et malesuada fames ac turpis. ",
    "Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. ",
    "Eu lobortis elementum nibh tellus molestie. ",
    "Sem et tortor consequat id porta nibh venenatis cras.",
    "Augue interdum velit euismod in pellentesque. ",
    "Et odio pellentesque diam volutpat commodo sed egestas egestas. ",
    "Id semper risus in hendrerit gravida. ",
    "Volutpat sed cras ornare arcu dui vivamus arcu felis. ",
    "Faucibus turpis in eu mi. ",
    "Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. ",
    "Nisi quis eleifend quam adipiscing vitae proin. ",
    "Eros in cursus turpis massa. ",
    "Donec ac odio tempor orci dapibus ultrices in iaculis. ",
    "Lectus urna duis convallis convallis tellus id. ",
    "Et odio pellentesque diam volutpat commodo sed. ",
    "Sit amet cursus sit amet. ",
    "Enim neque volutpat ac tincidunt vitae semper quis lectus. ",
    "Diam quis enim lobortis scelerisque fermentum dui. ",
    "Phasellus faucibus scelerisque eleifend donec. ",
    "Natoque penatibus et magnis dis parturient montes. ",
    "Aliquet risus feugiat in ante metus dictum at tempor. ",
    "Vulputate mi sit amet mauris. ",
    "Laoreet id donec ultrices tincidunt arcu non. ",
    "semper risus in hendrerit gravida rutrum quisque non. ",
    "Id diam vel quam elementum pulvinar etiam non quam lacus. ",
    "Cras pulvinar mattis nunc sed. ",
    "Aliquet lectus proin nibh nisl condimentum id. ",
    "Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. ",
    "Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. ",
    "Mattis aliquam faucibus purus in massa. ",
    "Sit amet consectetur adipiscing elit ut aliquam purus. ",
    "Malesuada fames ac turpis egestas. ",
    "Praesent semper feugiat nibh sed pulvinar proin gravida. ",
    "Quis enim lobortis scelerisque fermentum. ",
    "Nulla facilisi cras fermentum odio. ",
    "Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. ",
    "Dui id ornare arcu odio ut sem nulla pharetra. ",
    "Porta nibh venenatis cras sed felis.",
]