// This is generated by <proj root>./scripts/deploy/deploy.js and exported here by
// <proj root>/.scripts/updateFrontEnd.js
const addressConfig = require("./contractAddressesConfig.json");

module.exports = {
  addressConfig,
};
